apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: v6sf7sr53-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e5035894e92def8e7f744a77df01ac39f89548a9@sha256:98af8c9c357e1f45f9bcf6d22516f1530fad75bda293670110e3bbc7e79e5264
          name: container-image
